<?php
/**
 * @file
 */

error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

// RELS EXT URIs
define("ISLANDORA_MODEL_URI", 'http://islandora.ca/ontology/model#');

// CModels Helper Functions
module_load_include('inc', 'islandora_cmodel', 'includes/cmodel_helper_functions');
module_load_include('inc', 'islandora_cmodel', 'includes/hook_ingest_steps');

function islandora_cmodel_menu() {
  $urls['islandora/model/%islandora_cmodel'] = array(
    'title callback' => 'islandora_drupal_title',
    'title arguments' => array(2),
    'page callback' => 'islandora_view_object',
    'page arguments' => array(2),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'islandora_object_access_callback',
    'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 2),
  );

  $urls['islandora/model/%islandora_cmodel/content'] = array(
    'title' => 'Content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_related_objects_form', 2, 'islandora:specimen_cmodel', array('hasModel')),
    'access callback' => true,
    //    'access arguments' => array(array(ISLANDORA_VIEW_OBJECTS), 2),
    'type' => MENU_LOCAL_TASK,
  );

  return $urls;
}

/**
 * islandora_cmodel_action_title
 *
 * @param $action
 * @param $cmodel
 *
 * @return string
 *
 * Generates a page title given an 'action' and a 'cmodel'.
 *
 * For example:
 *
 *    Add Specimen
 *    Ingest Project
 */
function islandora_cmodel_action_title($action, $cmodel){
  return "{$action} {$cmodel->label}";
}

/**
 * Implements hook_theme
 */
function islandora_cmodel_theme($existing, $type, $theme, $path) {
  $themes['cmodel'] = array(
    'file' => 'theme/theme.inc',
    'template' => 'theme/cmodel',
    'variables' => array(
      'object' => NULL,
    ),
  );

  return $themes;
}

/**
 * Implements hook_islandora_object_alter
 *
 * This function creates a fedora:hasModel relationship between the $object
 * and all of it's CModel's supertypes. Should not be run for CModels.
 */
function islandora_cmodel_islandora_object_alter($object, array &$context) {
  $models = $object->models;
  $cm = in_array('fedora-system:ContentModel-3.0', $models);
  if($context['action'] == 'ingest' and !$cm){
    // Parent CModel
    // Don't use the islandora_object_parent_model function. It only works for
    // objects that have been fully ingested.
    $models = $object->models;
    $cmodel_id = $models[0];

    // Merges the object's models with
    $models = array_merge($object->models, islandora_cmodel_supertypes($cmodel_id));
    $object->models = $models;

    // Creates a hasParentModel relationship towards the CModel initially chosen.
    $object->relationships->registerNamespace('islandora-model', ISLANDORA_MODEL_URI);
    $object->relationships->add(ISLANDORA_MODEL_URI, 'hasParentModel', $cmodel_id);
  }
}

/**
 *
 */
function islandora_cmodel_fedora_system_ContentModel_3_0_islandora_object_alter($object, &$context){
  if($context['action'] == 'ingest'){
    $models = $object->models;
    $parent_id = $object->relationships->get(ISLANDORA_MODEL_URI, 'hasParentModel')[0]['object']['value'];

    $supertypes = islandora_cmodel_supertypes($parent_id);
    if($parent_id){
      $supertypes[] = $parent_id;
    }

    foreach($supertypes as $supertype){
      if(empty($object->relationships->get(ISLANDORA_RELS_EXT_URI, 'isSubtypeOf', $supertype))){
        $object->relationships->add(ISLANDORA_MODEL_URI, 'isSubtypeOf', $supertype);
      }
    }
  }
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object()
 *
 * Where CMODEL_PID = fedora-system:ContentModel-3.0
 */
function islandora_cmodel_fedora_system_ContentModel_3_0_islandora_view_object($object){
  $output = theme('cmodel', array('islandora_object' => $object));
  return array('cmodel' => $output);
}


/**
 * select_cmodel_form
 */
function select_cmodel_form($form, &$form_state) {
  $models = array();

  $stored_models = $form_state['islandora']['shared_storage']['models'];

  foreach($stored_models as $model_id){
    $model = islandora_cmodel_load($model_id);
    $models[$model->id] = $model->label;
  }

  $form['select'] = array(
    '#type' => 'select',
    '#title' => t('Content Model'),
    '#options' => $models,
  );

  return $form;
}



function select_cmodel_form_submit($form, &$form_state){
  $model = $form_state['values']['select'];
  $form_state['islandora']['shared_storage']['models'] = array($model);
}