<?php
/**
 * @file islandora_cmodel.module
 */

error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

/**
 * DEFINITION
 * __ISLANDORA_MODEL_URI__: http://islandora.ca/ontology/model#
 */
define("ISLANDORA_MODEL_URI", 'http://islandora.ca/ontology/model#');

module_load_include('inc', 'islandora_cmodel', 'includes/cmodel_functions');
module_load_include('inc', 'islandora_cmodel', 'includes/object_functions');
module_load_include('inc', 'islandora_cmodel', 'includes/hook_ingest_steps');

/**
 * # Implements hook_theme
 * ## CModel theme
 *
 * A render array based theme that allows users to hook in and add or remove
 * from the CModel page.
 *
 * Information passed to the theme includes the CModel's _supertypes_, _subtypes_,
 * and _relationships_.
 *
 * @see islandora_cmodel_page()
 * @see islandora_cmodel_preprocess_cmodel()
 * @see hook_theme()
 */
function islandora_cmodel_theme($existing, $type, $theme, $path) {
  module_load_include('inc', 'islandora_cmodel', 'theme/cmodel.page');
  $themes['cmodel'] = array(
    'file' => 'theme/theme.inc',
    'function' => 'islandora_cmodel_page',
    'variables' => array(
      'object' => NULL,
    ),
  );
  return $themes;
}


/**
 * Implements hook_islandora_object_alter
 *
 * This function creates a fedora:hasModel relationship between the $object
 * and all of it's CModel's supertypes. It is not run for CModels.
 *
 * @see hook_islandora_object_alter()
 */
function islandora_cmodel_islandora_object_alter($object, array &$context) {
  $models = $object->models;
  $cm = in_array('fedora-system:ContentModel-3.0', $models);
  if($context['action'] == 'ingest' and !$cm){
    // Parent CModel
    // Don't use the islandora_object_parent_model function. It only works for
    // objects that have been fully ingested.
    $models = $object->models;
    $cmodel_id = $models[0];

    // Merges the object's models with
    $models = array_merge($object->models, islandora_cmodel_types($cmodel_id));
    $object->models = $models;

    // Creates a hasParentModel relationship towards the CModel initially chosen.
    $object->relationships->registerNamespace('islandora-model', ISLANDORA_MODEL_URI);
    $object->relationships->add(ISLANDORA_MODEL_URI, 'hasParentModel', $cmodel_id);
  }
}

/**
 * Implements hook_CMODEL_PID_islandora_object_alter
 *
 * where CMODEL = fedora-system:ContentMdoel-3.0
 *
 * @see hook_cmodel_pid_islandora_object_alter()
 */
function islandora_cmodel_fedora_system_ContentModel_3_0_islandora_object_alter($object, &$context){
  /** This function modifies Content Models on ingest. */
  if($context['action'] == 'ingest'){
    /** If an islandora-model:hasParentModel relationship is defined for this CModel, */
    $parent_id = $object->relationships->get(ISLANDORA_MODEL_URI, 'hasParentModel')[0]['object']['value'];

    $supertypes = islandora_cmodel_types($parent_id);

    /**
     * then an islandora-model:isSubtypeOf relationship is made between it, and all of its
     * parent's supertypes.
     */
    foreach($supertypes as $supertype){
      if(empty($object->relationships->get(ISLANDORA_RELS_EXT_URI, 'isSubtypeOf', $supertype))){
        $object->relationships->add(ISLANDORA_MODEL_URI, 'isSubtypeOf', $supertype);
      }
    }
  }
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object()
 *
 * Where CMODEL_PID = fedora-system:ContentModel-3.0
 *
 * @see islandora_cmodel_theme()
 * @see hook_CMODEL_PID_islandora_view_object()
 */
function islandora_cmodel_fedora_system_ContentModel_3_0_islandora_view_object($object){
  $output = theme('cmodel', array('islandora_object' => $object));
  return array('cmodel' => $output);
}


/**
 * select_cmodel_form
 *
 * @param $form
 * @param $form_state
 * @return mixed
 *
 * This form is called before the ingestion process for an Islandora Object
 * begins. This form displays a list of CModels the User is able to choose from.
 *
 * The select_cmodel_form is not displayed if there is only one option.
 *
 * @see islandora_cmodel_islandora_ingest_steps_alter()
 */
function select_cmodel_form($form, &$form_state) {
  $models = array();

  $stored_models = $form_state['islandora']['shared_storage']['models'];

  foreach($stored_models as $model_id){
    $model = islandora_cmodel_load($model_id);
    $models[$model->id] = $model->label;
  }

  $form['select'] = array(
    '#type' => 'select',
    '#title' => t('Content Model'),
    '#options' => $models,
  );

  return $form;
}

/**
 * select_cmodel_form_submit
 *
 * @param $form
 * @param $form_state
 *
 * @see select_cmodel_form()
 */
function select_cmodel_form_submit($form, &$form_state){
  $model = $form_state['values']['select'];
  $form_state['islandora']['shared_storage']['models'] = array($model);
}